#!/usr/bin/python3

import sys
from math import isqrt

def is_prime(num):
    if num < 2:
        return False
    if num == 2 or num == 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False

    i = 5
    w= 2
    while i * i <= num:
        if num % i == 0:
            return False
        i += w
        w = 6 - w
    return True

def factorize(num):
    factors = []
    sqrt_num = isqrt(num)
    for i in range(2, sqrt_num + 1):
        if num % i == 0:
            factors.append((i, num // i))
            break
    else:
        factors.append((1, num))
    return factors

def factor():
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename, "r") as file:
        numbers = [int(line.strip()) for line in file]
    
    for num in numbers:
        factorizations = factorize(num)
        print("{:d}=".format(num), end="")
        if factorizations:
            fact1, fact2 = factorizations[0]
            if fact1 > fact2:
                fact1, fact2 = fact2, fact1
            print("{}*{}".format(fact2, fact1))
        
        else:
            print("{}".format(num))

factor()

