#!/usr/bin/python3

import sys

def factorize(num):
	factors = []
    for i in range(2, num // 2 + 1):
        if num % i == 0:
            factors.append((i, num // i))
    return factors

def factor():
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename == sys.argv[1]
    with open(filename, "r") as file:
        num = [int(line.strip()) for line in file]

    for num in numbers:
        factorization = factorize(num)
        print("{:d}".format(num), end="")
        if factorization:
            for facts in factorization:
                print("{} = {} * {}".format(num, facts[0], facts[1]), end="")
        else:
            print("{}".format(num), end="")
        print()

if __name__ == "__main__":
    factor()
